apiVersion: v1
kind: Secret
metadata:
  name: bitcoind-config
  namespace: monitoring
type: Opaque
stringData:
  bitcoin.conf: |
    server=1
    txindex=1
    printtoconsole=1

    rpcuser=bitcoin
    rpcpassword=bitcoinpw

    [regtest]
    regtest=1
    rpcbind=0.0.0.0
    rpcport=8332
    rpcallowip=10.0.0.0/8

