services:
  bitcoind:
    image: ruimarinho/bitcoin-core:24.0.1
    container_name: bitcoind
    command:
      -printtoconsole
      -server
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -rpcuser=bitcoin
      -rpcpassword=bitcoinpw
      -txindex
      -regtest
      -rpcport=8332 
    ports:
      - "8332:8332"
    volumes:
      - bitcoin-data:/bitcoin

  observer:
    build: ./observer
    container_name: observer
    depends_on:
      - bitcoind
    environment:
      BITCOIN_RPC_URL: "http://bitcoind:8332"
      BITCOIN_RPC_USER: "bitcoin"
      BITCOIN_RPC_PASSWORD: "bitcoinpw"
      INTERVAL_SEC: "10"
      METRICS_ADDR: ":9100"
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    depends_on:
      - observer
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    volumes:
      - ./manager/alertmanager.yml:/etc/manager/alertmanager.yml
    ports:
      - "9093:9093"
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      
volumes:
  bitcoin-data:
  grafana-data: