apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observer
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: observer
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
