apiVersion: apps/v1
kind: Deployment 
metadata:
  name: observer
  labels:
    app: observer
spec:
  replicas: 1  # 
  selector:
    matchLabels:
      app: observer
  template:   # observer pod 템플릿
    metadata:
      labels:
        app: observer
    spec:
      containers:
      - name: observer
        image: blockchain-gitops-observer:0.1.2
        env:
        - name: BITCOIN_RPC_URL
          valueFrom:
            configMapKeyRef:
              name: observer-config
              key: BITCOIN_RPC_URL
        - name: INTERVAL_SEC
          valueFrom:
            configMapKeyRef:
              name: observer-config
              key: INTERVAL_SEC
        - name: METRICS_ADDR
          valueFrom:
            configMapKeyRef:
              name: observer-config
              key: METRICS_ADDR
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              name: bitcoind-secret
              key: rpcuser
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitcoind-secret
              key: rpcpassword
        ports:
        - containerPort: 9100


