apiVersion: v1
kind: Service
metadata:
  name: observer 
  labels:
    app: observer
spec:
  selector:
    app: observer 
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  type: ClusterIP