apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoind
  namespace: monitoring
spec:
  serviceName: bitcoind
  replicas: 1
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
      - name: bitcoind
        image: ruimarinho/bitcoin-core:24.0.1
        ports:
        - containerPort: 8332
        command: ["bitcoind"]
        args:
          - -conf=/etc/bitcoin/bitcoin.conf
          - -regtest
          - -datadir=/bitcoin
        volumeMounts:
        - name: bitcoin-data
          mountPath: /bitcoin
        - name: bitcoind-config
          mountPath: /etc/bitcoin
          readOnly: true
      volumes:
      - name: bitcoind-config
        secret:
          secretName: bitcoind-config
  volumeClaimTemplates:
  - metadata:
      name: bitcoin-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
