apiVersion: v1
kind: Secret
metadata:
  name: bitcoind-secret
  namespace: monitoring 
type: Opaque
data:
  rpcuser: Yml0Y29pbg==       # base64("bitcoin")
  rpcpassword: Yml0Y29ucHc=   # base64("bitcoinpw")
